version: '3'
services:
  database:
    image: postgres
    restart: always
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
      - ./create_database.sql:/docker-entrypoint-initdb.d/create_database.sql

    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres